modLoader="javafml"
loaderVersion="[${fml_min},)"
license="${mod_license}"

[[mods]]
modId="potiondescriptions"
version="${mod_version}"
displayName="${mod_name}"
logoFile="examplemod.png"
authors="${mod_author}"
description="${mod_description}"

[[dependencies.potiondescriptions]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="CLIENT"

[[dependencies.potiondescriptions]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.potiondescriptions]]
    modId="botania"
    mandatory=false
    versionRange="[${botania_version},)"
    ordering="BEFORE"
    side="CLIENT"

[[dependencies.potiondescriptions]]
    modId="reliquary"
    mandatory=false
    versionRange="[${reliquary_version},)"
    ordering="BEFORE"
    side="CLIENT"
